"""add unique constraint user_schedule

Revision ID: 1c8e94757025
Revises: 67bb78d3f0f7
Create Date: 2026-04-12 09:18:12.485329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8e94757025'
down_revision = '67bb78d3f0f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedules', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_schedule_date', ['user_id', 'schedule_date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_schedules', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_schedule_date', type_='unique')

    # ### end Alembic commands ###
