"""add completed_at to study_plans

Revision ID: d8caaf3a5d18
Revises: 9ac7aab1b2fc
Create Date: 2026-04-17 00:30:01.137350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8caaf3a5d18'
down_revision = '9ac7aab1b2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_plans', schema=None) as batch_op:
        batch_op.drop_column('completed_at')

    # ### end Alembic commands ###
